### ISSUE TITLE
Add on clan chat event

### ISSUE THREAD

**Issue by Eufranio** [Tuke-Nuke/TuSKe#4]

**Comment by Tuke-Nuke** [comment]
I don't know if were you that suggested it to me couple days ago but now I've searched about it and found that doesn't exist any event for it in SimpleClans' api. I've suggested the current author if he can do it and will say whenever he answer me.

I could just make a workaround with `on command "."` inside of TuSKe but it won't work neither since SimpleClans uses exactly that event to create its commands, and with that, with that, it wouldn't be cancellable.

**Comment by Eufranio** [comment]
Couldn't you use Reflection? Yes that was me, I tries what you suggested (on command) and it didn't work, so I was hoping you could add it to TuSKe :/

**Comment by Tuke-Nuke** [comment]
Not much, reflection doesn't havae that purposes. The problem is that the event `on command "."` from SimpleClans will register before TuSKe, this way I can't prevent it from sending a chat.

**Comment by Eufranio** [comment]
What about `loadbefore: [SimpleClans]` in plugin.yml?

**Comment by Tuke-Nuke** [comment]
I never tried it, but I think it won't be possible to register the stuffs from SimpleClans, like event and expressions

**Comment by Eufranio** [comment]
Skellett uses that to register its stuff before TuSKe and Umbaska 😛

**Comment by Eufranio** [comment]
Skellett uses that to register its stuff before TuSKe and Umbaska 😛

**Comment by Tuke-Nuke** [comment]
Yeah, which is a shame, this option should be used in particular cases where you need to do something before another plugin (in this case), and not try to override it.

**Comment by Eufranio** [comment]
how is it going?

**Comment by Tuke-Nuke** [comment]
Hey, I have been off for few days, I might come back to TuSKe development next days probably, and if I remember correctly, I made a base ready, it's just need to enable to Skript and then test if it is working.

**Comment by Eufranio** [comment]
Great!

**Comment by Tuke-Nuke** [comment]
Added in last release.
